apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: run-predictions-
spec:
  serviceAccountName: workflow
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 64Gi
  entrypoint: main
  arguments:
    parameters:
      - name: params-conf-list
        value: '[
            {"QUARTER": 1},
            {"QUARTER": 2}
            ]'

  templates:
    - name: main
      dag:
        tasks:
          - name: predictions
            template: run-predictions
            arguments:
              parameters:
                - name: QUARTER
                  value: "{{item.QUARTER}}"
            # Pass the inputs to the task using "withParam"
            withParam: "{{workflow.parameters.params-conf-list}}"

    # Worker templat
    - name: run-predictions
      inputs:
          parameters:
            - name: QUARTER
      nodeSelector:
        nvidia.com/gpu.product: "NVIDIA-H100-PCIe"
      container:
        image: inseefrlab/onyxia-vscode-pytorch:py3.12.4-gpu
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 1
        command: ["/bin/bash", -c]
        args:
          - |
            git clone https://${GIT_USERNAME}:${GIT_TOKEN}@github.com/${GIT_USERNAME}/classif-win-challenge.git &&
            cd classif-win-challenge/ &&
            pip install -r requirements.txt &&
            python 4-classif-llm.py --languages en --quarter {{inputs.parameters.QUARTER}}

        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          # env var for s3 connexion
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: accessKey
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: secretKey
          - name: AWS_DEFAULT_REGION
            value: us-east-1
          - name: AWS_S3_ENDPOINT
            value: minio.lab.sspcloud.fr
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token
                key: token
          - name: GIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: github-info
                key: username
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-info
                key: token
