apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: run-pipeline-
spec:
  serviceAccountName: workflow
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 64Gi
  entrypoint: main
  arguments:
    parameters:
      - name: params-conf-list-translate-desc
        value: '[
            {"THIRD": 1},
            {"THIRD": 2},
            {"THIRD": 3}
            ]'
      - name: params-conf-list-prompt
        value: '[
            {"THIRD": 1},
            {"THIRD": 2},
            {"THIRD": 3}
            ]'
      - name: params-conf-list-predictions
        value: '[
            {"THIRD": 1},
            {"THIRD": 2},
            {"THIRD": 3}
            ]'

  templates:
    - name: main
      dag:
        tasks:
        # Task 1
          - name: run-detect-lang
            template: run-detect-lang

        # Task 2a
          - name: run-translate-desc-en
            dependencies: [ run-detect-lang ]
            template: run-translate-desc-en
            arguments:
              parameters:
                - name: THIRD
                  value: "{{item.THIRD}}"
            # Pass the inputs to the task using "withParam"
            withParam: "{{workflow.parameters.params-conf-list-translate-desc}}"

        # Task 2b
          - name: run-translate-desc
            dependencies: [ run-detect-lang ]
            template: run-translate-desc

        # Task 3a
          - name: run-prompts-en
            dependencies: [ run-translate-desc-en ]
            template: run-prompts-en
            arguments:
              parameters:
                - name: THIRD
                  value: "{{item.THIRD}}"
            # Pass the inputs to the task using "withParam"
            withParam: "{{workflow.parameters.params-conf-list-prompt}}"

        # Task 3b
          - name: run-prompts
            dependencies: [  run-translate-desc ]
            template: run-prompts

        # Task 4a
          - name: run-predictions-en
            dependencies: [ run-prompts-en ]
            template: run-predictions-en
            arguments:
              parameters:
                - name: THIRD
                  value: "{{item.THIRD}}"
            # Pass the inputs to the task using "withParam"
            withParam: "{{workflow.parameters.params-conf-list-predictions}}"

        # Task 4b
          - name: run-predictions
            dependencies: [ run-prompts ]
            template: run-predictions


    # Worker template 1
    - name: run-detect-lang
      nodeSelector:
        nvidia.com/gpu.product: "NVIDIA-H100-PCIe"
      container:
        image: thomasfaria/classif-win-challenge:main
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            nvidia.com/gpu: 1
        command: ["/bin/bash", -c]
        args:
          - |
            git clone https://${GIT_USERNAME}:${GIT_TOKEN}@github.com/${GIT_USERNAME}/classif-win-challenge.git &&
            cd classif-win-challenge/ &&
            pip install -r requirements.txt &&
            huggingface-cli login --token $HF_TOKEN &&
            python 1-detect-language.py

        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          # env var for s3 connexion
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: accessKey
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: secretKey
          - name: AWS_DEFAULT_REGION
            value: us-east-1
          - name: AWS_S3_ENDPOINT
            value: minio.lab.sspcloud.fr
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token
                key: token
          - name: GIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: github-info
                key: username
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-info
                key: token

    - name: run-translate-desc-en
      inputs:
        parameters:
          - name: THIRD
      nodeSelector:
        nvidia.com/gpu.product: "NVIDIA-H100-PCIe"
      container:
        image: thomasfaria/classif-win-challenge:main
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            nvidia.com/gpu: 1
        command: ["/bin/bash", -c]
        args:
          - |
            git clone https://${GIT_USERNAME}:${GIT_TOKEN}@github.com/${GIT_USERNAME}/classif-win-challenge.git &&
            cd classif-win-challenge/ &&
            pip install -r requirements.txt &&
            huggingface-cli login --token $HF_TOKEN &&
            export MC_HOST_s3=https://$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY@$AWS_S3_ENDPOINT &&
            python 2-translate-descriptions.py --description_col description_clean --title_col title_clean --languages en --third {{inputs.parameters.THIRD}} --use_s3 1

        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          # env var for s3 connexion
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: accessKey
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: secretKey
          - name: AWS_DEFAULT_REGION
            value: us-east-1
          - name: AWS_S3_ENDPOINT
            value: minio.lab.sspcloud.fr
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token
                key: token
          - name: GIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: github-info
                key: username
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-info
                key: token

    - name: run-translate-desc
      nodeSelector:
        nvidia.com/gpu.product: "NVIDIA-H100-PCIe"
      container:
        image: thomasfaria/classif-win-challenge:main
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            nvidia.com/gpu: 1
        command: ["/bin/bash", -c]
        args:
          - |
            git clone https://${GIT_USERNAME}:${GIT_TOKEN}@github.com/${GIT_USERNAME}/classif-win-challenge.git &&
            cd classif-win-challenge/ &&
            pip install -r requirements.txt &&
            huggingface-cli login --token $HF_TOKEN &&
            export MC_HOST_s3=https://$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY@$AWS_S3_ENDPOINT &&
            python 2-translate-descriptions.py --description_col description_clean --title_col title_clean --languages \
              bg cs da de el es et fi fr ga hr hu it lt lv mt nl pl pt ro sk sl sv un --use_s3 1
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          # env var for s3 connexion
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: accessKey
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: secretKey
          - name: AWS_DEFAULT_REGION
            value: us-east-1
          - name: AWS_S3_ENDPOINT
            value: minio.lab.sspcloud.fr
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token
                key: token
          - name: GIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: github-info
                key: username
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-info
                key: token

    - name: run-prompts-en
      inputs:
        parameters:
          - name: THIRD
      nodeSelector:
        nvidia.com/gpu.product: "NVIDIA-H100-PCIe"
      container:
        image: thomasfaria/classif-win-challenge:main
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            nvidia.com/gpu: 1
        command: ["/bin/bash", -c]
        args:
          - |
            git clone https://${GIT_USERNAME}:${GIT_TOKEN}@github.com/${GIT_USERNAME}/classif-win-challenge.git &&
            cd classif-win-challenge/ &&
            pip install -r requirements.txt &&
            export MC_HOST_s3=https://$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY@$AWS_S3_ENDPOINT &&
            python 3-build-vdb.py --title_col "title_en" --description_col "description_en" --languages en --third {{inputs.parameters.THIRD}} --use_s3 1

        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          # env var for s3 connexion
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: accessKey
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: secretKey
          - name: AWS_DEFAULT_REGION
            value: us-east-1
          - name: AWS_S3_ENDPOINT
            value: minio.lab.sspcloud.fr
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token
                key: token
          - name: GIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: github-info
                key: username
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-info
                key: token

    - name: run-prompts
      nodeSelector:
        nvidia.com/gpu.product: "NVIDIA-H100-PCIe"
      container:
        image: thomasfaria/classif-win-challenge:main
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            nvidia.com/gpu: 1
        command: ["/bin/bash", -c]
        args:
          - |
            git clone https://${GIT_USERNAME}:${GIT_TOKEN}@github.com/${GIT_USERNAME}/classif-win-challenge.git &&
            cd classif-win-challenge/ &&
            pip install -r requirements.txt &&
            export MC_HOST_s3=https://$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY@$AWS_S3_ENDPOINT &&
            python 3-build-vdb.py --title_col "title_en" --description_col "description_en" --languages \
              bg cs da de el es et fi fr ga hr hu it lt lv mt nl pl pt ro sk sl sv un --use_s3 1

        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          # env var for s3 connexion
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: accessKey
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: secretKey
          - name: AWS_DEFAULT_REGION
            value: us-east-1
          - name: AWS_S3_ENDPOINT
            value: minio.lab.sspcloud.fr
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token
                key: token
          - name: GIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: github-info
                key: username
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-info
                key: token

    - name: run-predictions-en
      inputs:
        parameters:
          - name: THIRD
      nodeSelector:
        nvidia.com/gpu.product: "NVIDIA-H100-PCIe"
      container:
        image: thomasfaria/classif-win-challenge:main
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            nvidia.com/gpu: 1
        command: ["/bin/bash", -c]
        args:
          - |
            git clone https://${GIT_USERNAME}:${GIT_TOKEN}@github.com/${GIT_USERNAME}/classif-win-challenge.git &&
            cd classif-win-challenge/ &&
            pip install -r requirements.txt &&
            huggingface-cli login --token $HF_TOKEN &&
            export MC_HOST_s3=https://$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY@$AWS_S3_ENDPOINT &&
            python 4-classif-llm.py --languages en --third {{inputs.parameters.THIRD}} --use_s3 1

        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          # env var for s3 connexion
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: accessKey
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: secretKey
          - name: AWS_DEFAULT_REGION
            value: us-east-1
          - name: AWS_S3_ENDPOINT
            value: minio.lab.sspcloud.fr
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token
                key: token
          - name: GIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: github-info
                key: username
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-info
                key: token

    - name: run-predictions
      nodeSelector:
        nvidia.com/gpu.product: "NVIDIA-H100-PCIe"
      container:
        image: thomasfaria/classif-win-challenge:main
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            nvidia.com/gpu: 1
        command: ["/bin/bash", -c]
        args:
          - |
            git clone https://${GIT_USERNAME}:${GIT_TOKEN}@github.com/${GIT_USERNAME}/classif-win-challenge.git &&
            cd classif-win-challenge/ &&
            pip install -r requirements.txt &&
            huggingface-cli login --token $HF_TOKEN &&
            export MC_HOST_s3=https://$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY@$AWS_S3_ENDPOINT &&
            python 4-classif-llm.py --languages bg cs da de el es et fi fr ga hr hu it lt lv mt nl pl pt ro sk sl sv un --use_s3 1

        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          # env var for s3 connexion
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: accessKey
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: secretKey
          - name: AWS_DEFAULT_REGION
            value: us-east-1
          - name: AWS_S3_ENDPOINT
            value: minio.lab.sspcloud.fr
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token
                key: token
          - name: GIT_USERNAME
            valueFrom:
              secretKeyRef:
                name: github-info
                key: username
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-info
                key: token
